### ISSUE TITLE
Ability to sort the book feed randomly. 

### ISSUE THREAD

**Issue by avinashkanaujiya** [isaaclyman/bookoscope#2]
**Problem**

When a user has huge book library, it is difficult to explore the books. 

**Idea**

Having the ability to sort books randomly, might help surface different books everytime we open the app.

**Comment by isaaclyman** [comment]
That's an unconventional request, but I like it. The implementation could go a couple different ways:

- A "shuffle" button in the search bar. Every time you tap, the list of books is randomized.
- A "surprise me" button that randomly selects a book from your collection.

Would one of these meet your needs? I wouldn't expect either of them to persist if you close and re-open the app, unless there's a compelling reason the order should be saved.

**Comment by avinashkanaujiya** [comment]
I think one of those, will really help, preferably first. I don't think persisting them, will be of any use.

**Comment by isaaclyman** [comment]
The "shuffle" button is implemented in v1.3.0. The app package has been submitted and will be available as soon as it passes review.

**Comment by avinashkanaujiya** [comment]
Awesome
