### ISSUE TITLE
Sorting OPDS by newest entry

### ISSUE THREAD

**Issue by johnjf76** [isaaclyman/bookoscope#3]
Hi! Great App!

While I can search for individual books, it would be nice to be able to sort the OPDS by the newest entries in the OPDS repository. This would be VERY useful for my Calibre local OPDS library, as it would make downloading and adding to my ebook reader simpler and faster!

If you could do this as a future enhancement, that would be wonderful. Thanks for a great product!

John F.

**Comment by isaaclyman** [comment]
I like that idea a lot. The only problem is I'm not sure if OPDS servers reliably expose information about when items were added. I'll look over some of my reference feeds and see if this is possible.

**Comment by johnjf76** [comment]
Thanks!! 
    On Tuesday, October 15, 2024 at 07:51:18 PM EDT, Isaac Lyman ***@***.***> wrote:  
 
 


I like that idea a lot. The only problem is I'm not sure if OPDS servers reliably expose information about when items were added. I'll look over some of my reference feeds and see if this is possible.

**Comment by isaaclyman** [comment]
Okay, I've checked it out and OPDS doesn't typically report the date when something was added to your library. I could keep a history in the app, but since Bookoscope doesn't have cross-device sync, only the newest books _for the current device_ would appear at the top.

I will probably work on this since I would find it helpful as well, but can't make any promises about a timeline - could be a while before I get to it.

Thanks again for the suggestion.

**Comment by johnjf76** [comment]
Hi Issac!
Thanks again for your quick response! I don't know if this would help, but I mostly use Calibre for OPDS storage (like many other users). I don't know if there's a Calibre spec you could use for sorting, but there might be something there that's useful.
Again, no rush, and I understand this may not be possible. A sorting option would be nice to have, but the product itself is an amazing time saver for me as is. Thanks again!
John F.
    On Thursday, October 17, 2024 at 10:43:50 AM EDT, Isaac Lyman ***@***.***> wrote:  
 
 


Okay, I've checked it out and OPDS doesn't typically report the date when something was added to your library. I could keep a history in the app, but since Bookoscope doesn't have cross-device sync, only the newest books for the current device would appear at the top.

I will probably work on this since I would find it helpful as well, but can't make any promises about a timeline - could be a while before I get to it.

Thanks again for the suggestion.

**Comment by isaaclyman** [comment]
Working on implementation today.

**Comment by isaaclyman** [comment]
I've submitted version 1.5.0 for review; you can expect to get the update within a week, most likely.

The app now tracks titles it's seen before. This involves new data storage, so unfortunately it's not possible to do it retroactively; the first time you refresh your sources after the update, _all_ the titles will appear with the "New" label. But from there on out, only titles that are new or changed in the last two weeks will have the label.

"New" titles will be prioritized to the top of the feed when the search box is empty.

**Comment by johnjf76** [comment]
Wow, Thank you! And Happy New Year!
John F.
    On Friday, December 27, 2024 at 02:29:53 PM EST, Isaac Lyman ***@***.***> wrote:  
 
 


I've submitted version 1.5.0 for review; you can expect to get the update within a week, most likely.

The app now tracks titles it's seen before. This involves new data storage, so unfortunately it's not possible to do it retroactively; the first time you refresh your sources after the update, all the titles will appear with the "New" label. But from there on out, only titles that are new or changed in the last two weeks will have the label.

"New" titles will be prioritized to the top of the feed when the search box is empty.
